#!/bin/sh

regkey="fffe4d004b004100430033002d0048004700430051004e002d00430038005400500047002d00570039003400450050002d004400340042004d004500"

if [ -n "$regkey" ]; then
	[[ ! -d /Users/Shared/TechSmith ]] && /bin/mkdir /Users/Shared/TechSmith
	[[ ! -d /Users/Shared/TechSmith/Snagit ]] && /bin/mkdir /Users/Shared/TechSmith/Snagit
	/usr/bin/defaults write /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey RegKey -data "$regkey"
	/usr/bin/plutil -convert xml1 /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey.plist
	/bin/mv /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey.plist /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey
	/bin/chmod -R 777 /Users/Shared/TechSmith
	/bin/chmod a+x /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey
fi

ver=$(defaults read /Applications/Snagit.app/Contents/Info.plist CFBundleShortVersionString)

for USER_TEMPLATE in $(/bin/ls /System/Library/User\ Template)
do
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" DidTheOneOneRearrange -bool "TRUE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" Ran1.1Upgrade -bool "TRUE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" Ran3.3Upgrade -bool "TRUE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" SUEnableAutomaticChecks -bool "FALSE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" SUHasLaunchedBefore -bool "TRUE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" SULastCheckTime -date "2015-01-01 12:00:00 +0000"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" SUSendProfileInfo -bool "TRUE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" autosaveFolderLocation -string "/Users/Shared/TechSmith"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" currentCaptureMode -int 5
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" defaultCollapsed -bool "FALSE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" hasLaunchedSnagitPreviously -bool "TRUE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" lastLaunchedSnagitVersion -string "${ver}"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" lastNag -date "2015-01-01 12:00:00 +0000"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" lastUsedTool -int 2
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" newInstallSendAttempts -int 0
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" resetVideoData -bool "TRUE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" stampSubpath -string "/Stamps.localized"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" tutorialAssetsShown -bool "TRUE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" tutorialImageShown -bool "TRUE"
    /usr/bin/defaults write "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.TechSmith.Snagit" RearrangedForStepTool -bool "TRUE"
done

for USER in $(/bin/ls /Users | /usr/bin/grep -v "Shared\|\.")
do
    if [ ! USER = "Shared" ]; then
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" DidTheOneOneRearrange -bool "TRUE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" Ran1.1Upgrade -bool "TRUE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" Ran3.3Upgrade -bool "TRUE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" SUEnableAutomaticChecks -bool "FALSE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" SUHasLaunchedBefore -bool "TRUE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" SULastCheckTime -date "2015-01-01 12:00:00 +0000"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" SUSendProfileInfo -bool "TRUE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" autosaveFolderLocation -string "/Users/Shared/TechSmith"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" currentCaptureMode -int 5
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" defaultCollapsed -bool "FALSE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" hasLaunchedSnagitPreviously -bool "TRUE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" lastLaunchedSnagitVersion -string "${ver}"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" lastNag -date "2015-01-01 12:00:00 +0000"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" lastUsedTool -int 2
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" newInstallSendAttempts -int 0
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" resetVideoData -bool "TRUE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" stampSubpath -string "/Stamps.localized"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" tutorialAssetsShown -bool "TRUE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" tutorialImageShown -bool "TRUE"
        /usr/bin/defaults write "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit" RearrangedForStepTool -bool "TRUE"
        owner=$(/usr/bin/stat -f %Su:%Sg "/Users/${USER}/Library/Preferences")
        /usr/sbin/chown "${owner}" "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit.plist"
        /bin/chmod 600 "/Users/${USER}/Library/Preferences/com.TechSmith.Snagit.plist"
    fi
done