#!/bin/sh

regkey=""

if [ -n "$regkey" ]; then
  [[ ! -d "/Users/Shared/TechSmith/Snagit" ]] && /bin/mkdir -p "/Users/Shared/TechSmith/Snagit"
  /bin/echo "$regkey" > "/Users/Shared/TechSmith/Snagit/LicenseKey"
  /bin/chmod -R 777 "/Users/Shared/Snagit"
  /bin/chmod a+x "/Users/Shared/TechSmith/Snagit/LicenseKey"
fi
