#!/bin/sh

# Remove previous version(s) of Snagit from /Applications

oldVersions=$(ls -1 /Applications | grep "Snagit")

while IFS="\n" read -r oldVersion; do
   /bin/rm -rf "/Applications/${oldVersion}"
done < <(echo "${oldVersions}")
