#!/bin/sh

# Remove previous version(s) of Snagit from /Applications

oldVersions=$(ls /Applications | grep "Snagit")

for oldVersion in $oldVersions; do
   /bin/rm -rf "/Applications/${oldVersion}"
done
