#!/bin/bash

echo "Checking for previous Snagit versions..."
/usr/bin/find -E "/Applications" -iregex ".*[/]Snagit ?([0-9]{4})?[.]app" -type d -maxdepth 1 -prune -exec sh -c 'echo "Found previous version: {}\c"; if $( /bin/rm -fR "{}" ); then echo ".....REMOVED"; fi' \;

exit 0
