#!/bin/sh

# Remove previous version(s) of Camtasia from /Applications

oldVersions=$(ls -1 /Applications | grep "Camtasia")

for oldVersion in $oldVersions; do
   /bin/rm -rf "/Applications/${oldVersion}"
done
